# CONFIGURACIÓN DEL SITIO (personalización del sitio web)
# Guía: https://wowchemy.com/docs/getting-started/
# Documentación: https://wowchemy.com/docs/
# Este archivo está formateado usando la sintaxis YAML; obtenga más información en https://learnxinyminutes.com/docs/yaml/

# Apariencia

appearance:
  theme_day: minimal
  theme_night: minimal
  font: 'custom_font'
  font_size: L

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'A highly-customizable Hugo academic resume theme powered by Wowchemy website builder.'
    twitter: 'wowchemy'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Encabezado del sitio

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Pie de página del sitio

footer:
  copyright:
    notice: '© {year} Me. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localización

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Características del sitio

features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: dracula
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/<username>/<repository>'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensiones

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Seguridad

security:
  # Permitir marco para incrustar notas del orador en diapositivas
  allow_frame: true
